[package]
name = "sqlite3-parser-logos"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = "0.15.0"

[dev-dependencies]
criterion = "0.5.1"
sqlparser = "0.38.0"

[[bench]]
name = "parser_benchmark"
harness = false

[[bin]]
name = "analyze_results"
path = "benches/analyze_results.rs"
